import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { doc, setDoc } from 'firebase/firestore';

import { useAuth } from './auth-context';
import { db } from './firebase-client';

export type SupportedLanguage = 'en' | 'zh';
export type LanguagePreference = SupportedLanguage | null;

type TranslationValue = string;

type TranslationDictionary = Record<string, TranslationValue | ((vars?: Record<string, string | number>) => string)>;

const TRANSLATIONS: Record<SupportedLanguage, TranslationDictionary> = {
  en: {
    'language.english': 'English',
    'language.chinese': 'Chinese',
    'common.done': 'Done',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.hide': 'Hide',
    'common.show': 'Show',
    'common.search': 'Search',
    'common.user': 'User',
    'common.close': 'Close',
    'common.apply': 'Apply',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.noNotes': 'No notes',
    'common.unknownEmail': 'unknown@example.com',
    'common.minutesShort': (vars) => `${vars?.minutes}m`,
    'common.minutesLong': (vars) => `${vars?.minutes} min`,
    'tabs.dashboard': 'Dashboard',
    'tabs.tasks': 'Tasks',
    'tabs.calendar': 'Calendar',
    'tabs.exercise': 'Exercise',
    'tabs.diet': 'Diet',
    'tabs.settings': 'Settings',
    'theme.ocean': 'Ocean',
    'theme.sunset': 'Sunset',
    'theme.mint': 'Mint',
    'theme.lavender': 'Lavender',
    'theme.graphite': 'Graphite',
    'theme.rose': 'Rose',
    'settings.title': 'Settings',
    'settings.subtitle': 'Personalize your experience.',
    'settings.profile': 'Profile',
    'settings.you': 'You',
    'settings.logout': 'Log Out',
    'settings.theme': 'Theme',
    'settings.chooseLook': 'Choose Look',
    'settings.preferences': 'Preferences',
    'settings.dailyReminders': 'Daily reminders',
    'settings.cloudSync': 'Cloud sync',
    'settings.focusMode': 'Focus mode by default',
    'settings.language': 'Language',
    'settings.languageTitle': 'Display Language',
    'settings.languageHint': 'Ownly follows your device language until you choose English or Chinese.',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': '',
    'dashboard.spotlight': 'Daily Spotlight',
    'dashboard.spotlightTagline': 'Shape your routine.',
    'dashboard.spotlightIntro': 'Weather, wellness, and task momentum in one place.',
    'dashboard.editCards': 'Edit cards',
    'dashboard.done': 'Done',
    'dashboard.editSection': 'Edit Dashboard',
    'dashboard.editDescription': 'Choose which cards appear here and move them into the order that feels best.',
    'dashboard.showingNow': 'Showing now',
    'dashboard.hiddenCards': 'Hidden cards',
    'dashboard.allVisible': 'All cards are already on the dashboard.',
    'dashboard.weather.title': 'Local Weather',
    'dashboard.weather.subtitle': 'Weather spotlight',
    'dashboard.weather.loading': 'Finding local weather...',
    'dashboard.weather.allow': 'Allow location to show weather for where you are right now.',
    'dashboard.weather.enableServices': 'Turn on location services to see local weather.',
    'dashboard.weather.unavailable': 'Weather is unavailable right now. Pull to refresh later.',
    'dashboard.weather.area': 'Your area',
    'dashboard.weather.windLine': (vars) => `Wind ${vars?.windSpeed} mph · ${vars?.date} · ${vars?.time}`,
    'dashboard.weather.cityLine': (vars) => `${vars?.description} in ${vars?.city}`,
    'dashboard.exercise.title': 'Exercise',
    'dashboard.exercise.subtitle': 'Move today',
    'dashboard.exercise.meta': (vars) => `${vars?.sessions} sessions today · Goal ${vars?.goal} kcal`,
    'dashboard.diet.title': 'Diet',
    'dashboard.diet.subtitle': 'Calories left',
    'dashboard.diet.meta': (vars) => `${vars?.consumed} of ${vars?.target} kcal used today`,
    'dashboard.diet.macros': (vars) => `${vars?.protein}g protein · ${vars?.carbs}g carbs · ${vars?.fat}g fat`,
    'dashboard.tasks.title': 'Tasks',
    'dashboard.tasks.subtitle': 'Focus list',
    'dashboard.tasks.meta': (vars) => `${vars?.active} active tasks · ${vars?.due} due today · ${vars?.done} done`,
    'dashboard.hydration.title': 'Hydration',
    'dashboard.hydration.subtitle': 'Water tracker',
    'dashboard.hydration.meta1': 'Hydration logged today',
    'dashboard.hydration.meta2': (vars) => `${vars?.remaining} ml left to hit a 2.2L day`,
    'dashboard.habit.title': 'Habit Score',
    'dashboard.habit.subtitle': 'Consistency spotlight',
    'dashboard.habit.meta1': 'Habit score blends movement, hydration, and task follow-through.',
    'dashboard.habit.meta2': 'A small daily rhythm beats a perfect day.',
    'tasks.title': 'Tasks',
    'tasks.subtitle': 'Track tasks and tap + to add a new one.',
    'tasks.progress': 'Progress',
    'tasks.focus': 'Today Focus',
    'tasks.finished': (vars) => `${vars?.done} of ${vars?.total} tasks finished`,
    'tasks.completePercent': (vars) => `${vars?.percent}% complete`,
    'tasks.todo': 'To-Do List',
    'tasks.noActive': 'No active tasks. Nice work.',
    'tasks.completed': 'Completed',
    'tasks.noCompleted': 'Completed tasks will appear here.',
    'tasks.completedHidden': 'Completed tasks are hidden.',
    'tasks.general': 'General',
    'tasks.repeats': 'Repeats',
    'exercise.title': 'Exercise',
    'exercise.subtitle': 'Search activities, log sessions, and track calories.',
    'exercise.dailyBurn': 'Daily Burn',
    'exercise.todayBurned': 'Calories Burned Today',
    'exercise.setup': 'Setup',
    'exercise.setupHint': 'Calories/hour are estimated from MET values at your entered body weight.',
    'exercise.goal': (vars) => `Goal: ${vars?.goal} kcal`,
    'exercise.goalPercent': (vars) => `${vars?.percent}% of today\'s target`,
    'exercise.goalCalories': 'Goal (kcal)',
    'exercise.category': 'Categories',
    'exercise.library': 'Exercise Library',
    'exercise.searchPlaceholder': 'Search activity name',
    'exercise.duration': 'Duration (minutes)',
    'exercise.weight': 'Weight (kg)',
    'exercise.customName': 'Custom activity name',
    'exercise.customCalories': 'Calories per hour',
    'exercise.preview': 'Preview burn',
    'exercise.logSession': 'Save session',
    'exercise.updateSession': 'Update session',
    'exercise.cancelEdit': 'Cancel edit',
    'exercise.customSection': 'Custom Exercise',
    'exercise.editingSession': 'Editing session',
    'exercise.updateBelow': 'Update the details below, then save your changes.',
    'exercise.selectedPrompt': 'Select an exercise or enter custom',
    'exercise.sessionEstimate': 'Session estimate',
    'exercise.loggedToday': 'Logged Today',
    'exercise.noneToday': 'No exercise sessions logged yet today.',
    'exercise.noMatches': 'No activity matches this search in the selected category.',
    'diet.title': 'Diet',
    'diet.subtitle': 'Search foods, log calories, and track intake.',
    'diet.meals': 'Meals',
    'diet.commonFoods': 'Common Foods',
    'diet.searchPlaceholder': 'Search food name',
    'diet.targetCalories': 'Target calories',
    'diet.waterMl': 'Water (ml)',
    'diet.saveTargets': 'Save goals',
    'diet.caloriesLeft': 'Calories left',
    'diet.usedToday': (vars) => `${vars?.consumed} of ${vars?.target} kcal used today`,
    'diet.macros': (vars) => `${vars?.protein}g protein · ${vars?.carbs}g carbs · ${vars?.fat}g fat`,
    'diet.foods': 'Foods',
    'diet.quickAdd': 'Quick add',
    'diet.selectedFood': 'Selected food',
    'diet.servings': 'Servings',
    'diet.customFood': 'Custom food',
    'diet.customFoodName': 'Food name',
    'diet.customCalories': 'Calories per serving',
    'diet.customProtein': 'Protein per serving',
    'diet.customCarbs': 'Carbs per serving',
    'diet.customFat': 'Fat per serving',
    'diet.previewEntry': 'Preview entry',
    'diet.addEntry': 'Add to meal',
    'diet.updateEntry': 'Update entry',
    'diet.cancelEdit': 'Cancel edit',
    'diet.loggedForMeal': (vars) => `${vars?.meal} · ${vars?.calories} kcal`,
    'diet.noEntries': 'No foods logged for this meal yet.',
    'diet.noMatches': 'No foods match this search in the selected category.',
    'diet.breakfast': 'Breakfast',
    'diet.lunch': 'Lunch',
    'diet.dinner': 'Dinner',
    'diet.snack': 'Snack',
    'diet.staples': 'Staples',
    'diet.protein': 'Protein & Dairy',
    'diet.fruit': 'Fruit',
    'diet.vegetables': 'Vegetables',
    'diet.nuts': 'Nuts & Beans',
    'diet.snacks': 'Snacks & Drinks',
    'diet.mealCategory': 'Meals',
    'login.title': 'Your OWN workspace.',
    'login.subtitle': 'Log in to your account',
    'login.with': 'Log in with',
    'login.emailSection': 'or continue with email',
    'login.signIn': 'Sign In',
    'login.signUp': 'Sign Up',
    'login.email': 'Enter your email address...',
    'login.password': 'Password',
    'login.name': 'Your name',
    'login.continue': 'Continue',
    'login.terms': 'By continuing, you acknowledge that you understand and agree to the Terms & Conditions and Privacy Policy.',
    'calendar.title': 'Calendar',
    'calendar.subtitle': 'Your task events are auto-synced here.',
    'calendar.list': 'List',
    'calendar.day': 'Day',
    'calendar.threeDay': '3 Day',
    'calendar.week': 'Week',
    'calendar.month': 'Month',
    'calendar.year': 'Year',
    'calendar.emptyRange': 'No events in this time range. Add timed tasks in the Tasks tab.',
    'calendar.emptyDate': 'No events on this date. Add timed tasks in the Tasks tab.',
    'calendar.emptyYear': 'No events in this year. Add timed tasks in the Tasks tab.',
    'calendar.emptyDay': 'No events on this day. Add timed tasks in the Tasks tab.',
    'calendar.durationUnknown': 'Duration unknown',
    'calendar.unknownTime': 'Unknown time',
    'calendar.unknownSchedule': 'Unknown schedule',
    'calendar.repeats': 'Repeats',
    'calendar.noCompletedEvents': 'No completed events for this period.',
    'calendar.completedHidden': 'Completed tasks are hidden.',
    'calendar.eventFallbackTitle': 'Event',
    'calendar.uncategorized': 'Uncategorized',
    'calendar.editEvent': 'Edit Event',
    'taskEditor.titleCreate': 'Create Task',
    'taskEditor.titleEdit': 'Edit Task',
    'taskEditor.subtitle': 'Keep details clear so your calendar stays focused.',
    'taskEditor.sectionDetails': 'Task Details',
    'taskEditor.labelTitle': 'Title',
    'taskEditor.placeholderTitle': 'Title',
    'taskEditor.labelNotes': 'Notes',
    'taskEditor.placeholderNotes': 'Notes',
    'taskEditor.labelDateDuration': 'Date & Duration',
    'taskEditor.repeatLabel': 'Repeat task',
    'taskEditor.repeatSubtext': 'Automatically keep this on your schedule.',
    'taskEditor.sectionCategories': 'Categories',
    'taskEditor.newCategory': 'New Category',
    'taskEditor.placeholderNewCategory': 'New category name',
    'taskEditor.addCategory': 'Add Category',
    'taskEditor.saveChanges': 'Save Changes',
    'taskEditor.createTask': 'Create Task',
    'taskEditor.chooseDateTime': 'Choose Date & Time',
    'taskEditor.exactTime': 'Exact time',
    'taskEditor.durationShort': 'Duration (min)',
    'taskEditor.manualTimePlaceholder': '1:42',
    'taskEditor.durationPlaceholder': '60',
    'taskEditor.use24HourError': 'Use 24-hour format like 1:42 or 13:42.',
    'taskEditor.durationRangeError': 'Duration must be between 5 and 1440 minutes.',
    'taskEditor.categoryNameRequired': 'Category name is required.',
    'taskEditor.atLeastOneCategory': 'At least one category must remain.',
    'taskEditor.taskTitleRequired': 'Task title is required.',
    'taskEditor.selectCategory': 'Please select a category.',
    'taskEditor.validDateTime': 'Choose a valid date and time.',
    'taskEditor.chooseCategoryColor': 'Choose Category Color',
    'taskEditor.validHexColor': 'Use a valid hex color like #4C6FFF.',
    'taskEditor.deleteTaskTitle': 'Delete task?',
    'taskEditor.deleteTaskDescription': 'This event will be removed from your schedule and cannot be undone.',
  },
  zh: {
    'language.english': '英文',
    'language.chinese': '中文',
    'common.done': '完成',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.hide': '隐藏',
    'common.show': '显示',
    'common.search': '搜索',
    'common.user': '用户',
    'common.close': '关闭',
    'common.apply': '应用',
    'common.add': '添加',
    'common.create': '创建',
    'common.noNotes': '暂无备注',
    'common.unknownEmail': 'unknown@example.com',
    'common.minutesShort': (vars) => `${vars?.minutes}分`,
    'common.minutesLong': (vars) => `${vars?.minutes} 分钟`,
    'tabs.dashboard': '首页',
    'tabs.tasks': '任务',
    'tabs.calendar': '日历',
    'tabs.exercise': '运动',
    'tabs.diet': '饮食',
    'tabs.settings': '设置',
    'theme.ocean': '海洋',
    'theme.sunset': '日落',
    'theme.mint': '薄荷',
    'theme.lavender': '薰衣草',
    'theme.graphite': '石墨',
    'theme.rose': '玫瑰',
    'settings.title': '设置',
    'settings.subtitle': '自定义你的使用体验。',
    'settings.profile': '个人资料',
    'settings.you': '你',
    'settings.logout': '退出登录',
    'settings.theme': '主题',
    'settings.chooseLook': '选择外观',
    'settings.preferences': '偏好设置',
    'settings.dailyReminders': '每日提醒',
    'settings.cloudSync': '云同步',
    'settings.focusMode': '默认专注模式',
    'settings.language': '语言',
    'settings.languageTitle': '显示语言',
    'settings.languageHint': 'Ownly 会先跟随设备语言；你也可以随时切换为英文或中文。',
    'dashboard.title': '首页',
    'dashboard.subtitle': '',
    'dashboard.spotlight': '今日聚焦',
    'dashboard.spotlightTagline': '整理你的日常节奏。',
    'dashboard.spotlightIntro': '天气、健康和任务节奏都放在这里。',
    'dashboard.editCards': '编辑卡片',
    'dashboard.done': '完成',
    'dashboard.editSection': '编辑首页',
    'dashboard.editDescription': '选择要显示的卡片，并按你最顺手的顺序排列。',
    'dashboard.showingNow': '当前显示',
    'dashboard.hiddenCards': '已隐藏卡片',
    'dashboard.allVisible': '所有卡片都已经显示在首页。',
    'dashboard.weather.title': '本地天气',
    'dashboard.weather.subtitle': '天气聚焦',
    'dashboard.weather.loading': '正在获取本地天气...',
    'dashboard.weather.allow': '允许定位后，这里会显示你当前位置的天气。',
    'dashboard.weather.enableServices': '请打开定位服务以查看本地天气。',
    'dashboard.weather.unavailable': '暂时无法获取天气，稍后再试。',
    'dashboard.weather.area': '你所在地区',
    'dashboard.weather.windLine': (vars) => `风速 ${vars?.windSpeed} mph · ${vars?.date} · ${vars?.time}`,
    'dashboard.weather.cityLine': (vars) => `${vars?.city} · ${vars?.description}`,
    'dashboard.exercise.title': '运动',
    'dashboard.exercise.subtitle': '今日运动',
    'dashboard.exercise.meta': (vars) => `今天 ${vars?.sessions} 次 · 目标 ${vars?.goal} kcal`,
    'dashboard.diet.title': '饮食',
    'dashboard.diet.subtitle': '剩余热量',
    'dashboard.diet.meta': (vars) => `今天已用 ${vars?.consumed}/${vars?.target} kcal`,
    'dashboard.diet.macros': (vars) => `蛋白质 ${vars?.protein}g · 碳水 ${vars?.carbs}g · 脂肪 ${vars?.fat}g`,
    'dashboard.tasks.title': '任务',
    'dashboard.tasks.subtitle': '专注列表',
    'dashboard.tasks.meta': (vars) => `${vars?.active} 个进行中 · 今日到期 ${vars?.due} 个 · 已完成 ${vars?.done} 个`,
    'dashboard.hydration.title': '饮水',
    'dashboard.hydration.subtitle': '补水记录',
    'dashboard.hydration.meta1': '今日已记录饮水',
    'dashboard.hydration.meta2': (vars) => `距离 2.2L 目标还差 ${vars?.remaining} ml`,
    'dashboard.habit.title': '习惯分数',
    'dashboard.habit.subtitle': '连续性聚焦',
    'dashboard.habit.meta1': '习惯分数综合了运动、饮水和任务完成情况。',
    'dashboard.habit.meta2': '稳定的小节奏，胜过偶尔完美的一天。',
    'tasks.title': '任务',
    'tasks.subtitle': '跟踪任务，点击 + 新建任务。',
    'tasks.progress': '进度',
    'tasks.focus': '今日重点',
    'tasks.finished': (vars) => `已完成 ${vars?.done}/${vars?.total} 个任务`,
    'tasks.completePercent': (vars) => `完成度 ${vars?.percent}%`,
    'tasks.todo': '待办列表',
    'tasks.noActive': '当前没有进行中的任务，做得不错。',
    'tasks.completed': '已完成',
    'tasks.noCompleted': '已完成任务会显示在这里。',
    'tasks.completedHidden': '已完成任务已隐藏。',
    'tasks.general': '通用',
    'tasks.repeats': '重复',
    'exercise.title': '运动',
    'exercise.subtitle': '搜索运动、记录训练并追踪热量。',
    'exercise.dailyBurn': '今日消耗',
    'exercise.todayBurned': '今天燃烧的热量',
    'exercise.setup': '基础设置',
    'exercise.setupHint': '每小时热量会根据你填写的体重和 MET 数值估算。',
    'exercise.goal': (vars) => `目标：${vars?.goal} kcal`,
    'exercise.goalPercent': (vars) => `达到今日目标的 ${vars?.percent}%`,
    'exercise.goalCalories': '目标（kcal）',
    'exercise.category': '分类',
    'exercise.library': '运动库',
    'exercise.searchPlaceholder': '搜索运动名称',
    'exercise.duration': '时长（分钟）',
    'exercise.weight': '体重（kg）',
    'exercise.customName': '自定义运动名称',
    'exercise.customCalories': '每小时热量',
    'exercise.preview': '预计消耗',
    'exercise.logSession': '保存记录',
    'exercise.updateSession': '更新记录',
    'exercise.cancelEdit': '取消编辑',
    'exercise.customSection': '自定义运动',
    'exercise.editingSession': '正在编辑记录',
    'exercise.updateBelow': '在下方更新内容后保存即可。',
    'exercise.selectedPrompt': '选择一个运动或输入自定义内容',
    'exercise.sessionEstimate': '预计本次消耗',
    'exercise.loggedToday': '今日记录',
    'exercise.noneToday': '今天还没有记录运动。',
    'exercise.noMatches': '当前分类下没有匹配这次搜索的运动。',
    'diet.title': '饮食',
    'diet.subtitle': '搜索食物、记录热量并追踪摄入。',
    'diet.meals': '餐次',
    'diet.commonFoods': '常见食物',
    'diet.searchPlaceholder': '请输入食物名称',
    'diet.targetCalories': '目标热量',
    'diet.waterMl': '饮水（ml）',
    'diet.saveTargets': '保存目标',
    'diet.caloriesLeft': '剩余热量',
    'diet.usedToday': (vars) => `今天已用 ${vars?.consumed}/${vars?.target} kcal`,
    'diet.macros': (vars) => `蛋白质 ${vars?.protein}g · 碳水 ${vars?.carbs}g · 脂肪 ${vars?.fat}g`,
    'diet.foods': '食物库',
    'diet.quickAdd': '快速记录',
    'diet.selectedFood': '已选食物',
    'diet.servings': '份数',
    'diet.customFood': '自定义食物',
    'diet.customFoodName': '食物名称',
    'diet.customCalories': '每份热量',
    'diet.customProtein': '每份蛋白质',
    'diet.customCarbs': '每份碳水',
    'diet.customFat': '每份脂肪',
    'diet.previewEntry': '预览记录',
    'diet.addEntry': '加入餐次',
    'diet.updateEntry': '更新记录',
    'diet.cancelEdit': '取消编辑',
    'diet.loggedForMeal': (vars) => `${vars?.meal} · ${vars?.calories} kcal`,
    'diet.noEntries': '这个餐次还没有记录食物。',
    'diet.noMatches': '当前分类下没有匹配这次搜索的食物。',
    'diet.breakfast': '早餐',
    'diet.lunch': '午餐',
    'diet.dinner': '晚餐',
    'diet.snack': '加餐',
    'diet.staples': '主食',
    'diet.protein': '肉蛋奶',
    'diet.fruit': '水果',
    'diet.vegetables': '蔬菜',
    'diet.nuts': '豆类坚果',
    'diet.snacks': '零食饮料',
    'diet.mealCategory': '整餐',
    'login.title': '你的 OWN 工作空间。',
    'login.subtitle': '登录你的账户',
    'login.with': '登录方式',
    'login.emailSection': '或使用邮箱继续',
    'login.signIn': '登录',
    'login.signUp': '注册',
    'login.email': '输入你的邮箱地址...',
    'login.password': '密码',
    'login.name': '你的名字',
    'login.continue': '继续',
    'login.terms': '继续即表示你已理解并同意条款与条件以及隐私政策。',
    'calendar.title': '日历',
    'calendar.subtitle': '你的任务事件会自动同步到这里。',
    'calendar.list': '列表',
    'calendar.day': '日',
    'calendar.threeDay': '3天',
    'calendar.week': '周',
    'calendar.month': '月',
    'calendar.year': '年',
    'calendar.emptyRange': '这个时间范围内没有事件。请到任务页添加定时任务。',
    'calendar.emptyDate': '这一天没有事件。请到任务页添加定时任务。',
    'calendar.emptyYear': '这一年还没有事件。请到任务页添加定时任务。',
    'calendar.emptyDay': '今天没有事件。请到任务页添加定时任务。',
    'calendar.durationUnknown': '时长未知',
    'calendar.unknownTime': '时间未知',
    'calendar.unknownSchedule': '日程未知',
    'calendar.repeats': '重复',
    'calendar.noCompletedEvents': '当前时间范围内没有已完成事件。',
    'calendar.completedHidden': '已完成任务已隐藏。',
    'calendar.eventFallbackTitle': '事件',
    'calendar.uncategorized': '未分类',
    'calendar.editEvent': '编辑任务',
    'taskEditor.titleCreate': '新建任务',
    'taskEditor.titleEdit': '编辑任务',
    'taskEditor.subtitle': '把细节整理清楚，让你的日程更专注。',
    'taskEditor.sectionDetails': '任务详情',
    'taskEditor.labelTitle': '标题',
    'taskEditor.placeholderTitle': '请输入标题',
    'taskEditor.labelNotes': '备注',
    'taskEditor.placeholderNotes': '请输入备注',
    'taskEditor.labelDateDuration': '日期和时长',
    'taskEditor.repeatLabel': '重复任务',
    'taskEditor.repeatSubtext': '自动保留在你的日程中。',
    'taskEditor.sectionCategories': '分类',
    'taskEditor.newCategory': '新分类',
    'taskEditor.placeholderNewCategory': '请输入分类名称',
    'taskEditor.addCategory': '添加分类',
    'taskEditor.saveChanges': '保存更改',
    'taskEditor.createTask': '创建任务',
    'taskEditor.chooseDateTime': '选择日期和时间',
    'taskEditor.exactTime': '精确时间',
    'taskEditor.durationShort': '时长（分钟）',
    'taskEditor.manualTimePlaceholder': '1:42',
    'taskEditor.durationPlaceholder': '60',
    'taskEditor.use24HourError': '请使用 24 小时格式，例如 1:42 或 13:42。',
    'taskEditor.durationRangeError': '时长必须在 5 到 1440 分钟之间。',
    'taskEditor.categoryNameRequired': '分类名称不能为空。',
    'taskEditor.atLeastOneCategory': '至少要保留一个分类。',
    'taskEditor.taskTitleRequired': '任务标题不能为空。',
    'taskEditor.selectCategory': '请选择一个分类。',
    'taskEditor.validDateTime': '请选择有效的日期和时间。',
    'taskEditor.chooseCategoryColor': '选择分类颜色',
    'taskEditor.validHexColor': '请输入有效的十六进制颜色，例如 #4C6FFF。',
    'taskEditor.deleteTaskTitle': '删除任务？',
    'taskEditor.deleteTaskDescription': '这个事件会从你的日程中移除，且无法撤销。',
  },
};

const LANGUAGE_LOCALES: Record<SupportedLanguage, string> = {
  en: 'en-US',
  zh: 'zh-CN',
};

type LanguageContextValue = {
  languagePreference: LanguagePreference;
  effectiveLanguage: SupportedLanguage;
  localeTag: string;
  setLanguagePreference: (value: SupportedLanguage) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function normalizeLanguagePreference(value: unknown): LanguagePreference {
  return value === 'zh' || value === 'en' ? value : null;
}

function detectSystemLanguage(): SupportedLanguage {
  const locale = Intl.DateTimeFormat().resolvedOptions().locale.toLowerCase();
  if (locale.startsWith('zh')) {
    return 'zh';
  }
  return 'en';
}

function interpolate(template: string, vars?: Record<string, string | number>) {
  if (!vars) {
    return template;
  }

  return template.replace(/\{\{(.*?)\}\}/g, (_, key) => String(vars[key.trim()] ?? ''));
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [languagePreference, setLanguagePreferenceState] = useState<LanguagePreference>(null);

  useEffect(() => {
    setLanguagePreferenceState(normalizeLanguagePreference(user?.languagePreference));
  }, [user?.languagePreference]);

  const effectiveLanguage = languagePreference ?? detectSystemLanguage();
  const localeTag = LANGUAGE_LOCALES[effectiveLanguage];

  const setLanguagePreference = useCallback(
    (value: SupportedLanguage) => {
      setLanguagePreferenceState(value);

      if (user && db) {
        void setDoc(
          doc(db, 'users', user.id),
          {
            languagePreference: value,
            updatedAt: Date.now(),
          },
          { merge: true }
        ).catch((error) => {
          console.error('Failed to update language preference', error);
        });
      }
    },
    [user]
  );

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      const dictionary = TRANSLATIONS[effectiveLanguage];
      const entry = dictionary[key] ?? TRANSLATIONS.en[key] ?? key;

      if (typeof entry === 'function') {
        return entry(vars);
      }

      return interpolate(entry, vars);
    },
    [effectiveLanguage]
  );

  const value = useMemo(
    () => ({
      languagePreference,
      effectiveLanguage,
      localeTag,
      setLanguagePreference,
      t,
    }),
    [effectiveLanguage, languagePreference, localeTag, setLanguagePreference, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used inside a LanguageProvider');
  }

  return context;
}
